config/routes.rb
Rails.application.routes.draw do

  root "public/homes#top"
  get '/about' => 'public/homes#about'
  get '/admin' => 'admin/homes#top'

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do
    resources :items, only: [:index, :show]
    get 'customers/check'
    get 'customers/mypage', to: 'customers#show', as: 'mypage'
    get 'customers/information/edit', to: 'customers#edit', as: 'edit_information'
    patch 'customers/information', to: 'customers#update'
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :cart_items, only: [:create, :index, :update, :destroy] do
      collection do
        delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post '/orders/confirm' => 'orders#confirm', as: 'confirm'
        get '/orders/complete' => 'orders#complete', as: 'complete'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  
  end 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
belongs_to :customer
belongs_to :item

validates :quantity, presence: true

def subtotal
    (item.tax_excluded_price * 1.1).round * quantity
end

end

app/models/customer.rb
class Customer < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (is_quit_status == false)
  end

  def name
    last_name + first_name
  end

  def name_kana
    last_name_kana + first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  belongs_to :genre, optional: true

  validates :name, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    # メソッドに対して引数を設定し、引数に設定した値に画像のサイズを変換するように設定
    image.variant(resize_to_fit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :items, through: :cart_item
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum orders_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  #enum production_status:{impossible:0, before:1, doing:2, completion:3}
  enum production_status:{着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}

  def subtotal
    (item.tax_excluded_price * quantity.to_i).to_i
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      @items = Item.all
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :tax_excluded_price, :image, :is_sale_status, :genre_id)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/items/edit.html.erb
<%= form_with model: @item, url: admin_item_path, local:true do |f| %>
<table>
    <tbody>
      <tr>
        <th>商品画像</th>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <th>商品名</th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :description %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "選択してください"} %></td>
      </tr>
      <tr>
        <th>税抜価格</th>
        <td><%= f.number_field :tax_excluded_price %>円</td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td>
          <%= f.radio_button :is_sale_status, "true" %>販売中
          <%= f.radio_button :is_sale_status, "false" %>販売停止中
        </td>
      </tr>
    </tbody>
  </table>
  <%= f.submit '保存' %>
  <% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admin_item_path(item.id) %></td>
      <td><%= item.tax_excluded_price.to_s(:delimited) %></td>
      <td><%= item.genre.name %></td>
      <td>
        <strong>
          <% if item.is_sale_status %>
            販売中
          <% elsif %>
            販売停止中
          <% end %>
        </strong>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<%= form_with model: @item, url: admin_items_path, local:true do |f| %>
  <table>
    <tbody>
      <tr>
        <th>商品画像</th>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <th>商品名</th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :description %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "--選択してください--"} %></td>
      </tr>
      <tr>
        <th>税抜価格</th>
        <td><%= f.number_field :tax_excluded_price %>円</td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td>
          <%= f.radio_button :is_sale_status, "true" %>販売中
          <%= f.radio_button :is_sale_status, "false" %>販売停止中
        </td>
      </tr>
    </tbody>
  </table>
  <%= f.submit '登録' %>
  <% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>
<%= image_tag @item.image, size: "300x300" %>

<table>
  <tbody>
    <tr>
      <th>商品名</th>
      <td><%= @item.name %></td>
    </tr>
     <tr>
      <th>商品説明</th>
      <td><%= @item.description %></td>
    </tr>
     <tr>
      <th>税込価格<br>(税抜価格)</th>
      <td><%= (@item.tax_excluded_price * 1.1).to_i %> (<%= @item.tax_excluded_price.to_s(:delimited) %>) 円</td>
    </tr>
     <tr>
      <th>ジャンル</th>
      <td><%= @item.genre.name %></td>
    </tr>
     <tr>
      <th>販売ステータス</th>
      <td>
        <strong>
          <% if @item.is_sale_status %>
            販売中
          <% elsif %>
            販売停止中
          <% end %>
        </strong>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_admin_item_path(@item) %> <%= link_to '削除', admin_item_path(@item), method: :delete, "data-confirm" => "本当に削除しますか？" %>