config/routes.rb
Rails.application.routes.draw do

  root "public/homes#top"
  get '/about' => 'public/homes#about'
  get '/admin' => 'admin/homes#top'

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do
    resources :items, only: [:index, :show]
    get 'customers/check'
    get 'customers/mypage', to: 'customers#show', as: 'mypage'
    get 'customers/information/edit', to: 'customers#edit', as: 'edit_information'
    patch 'customers/information', to: 'customers#update'
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :cart_items, only: [:create, :index, :update, :destroy] do
      collection do
        delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post '/orders/confirm' => 'orders#confirm', as: 'confirm'
        get '/orders/complete' => 'orders#complete', as: 'complete'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  
  end 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
belongs_to :customer
belongs_to :item

validates :quantity, presence: true

def subtotal
    (item.tax_excluded_price * 1.1).round * quantity
end

end

app/models/customer.rb
class Customer < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (is_quit_status == false)
  end

  def name
    last_name + first_name
  end

  def name_kana
    last_name_kana + first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  belongs_to :genre, optional: true

  validates :name, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    # メソッドに対して引数を設定し、引数に設定した値に画像のサイズを変換するように設定
    image.variant(resize_to_fit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :items, through: :cart_item
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum orders_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  #enum production_status:{impossible:0, before:1, doing:2, completion:3}
  enum production_status:{着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}

  def subtotal
    (item.tax_excluded_price * quantity.to_i).to_i
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<% if admin_signed_in? %>
  <li class="nav-item">
    <%= link_to admin_items_path, class: 'btn btn-outline-secondary w-auto' do %>
      商品一覧
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_customers_path, class: 'btn btn-outline-secondary w-auto' do %>
      会員一覧
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_orders_path, class: 'btn btn-outline-secondary w-auto' do %>
      注文履歴一覧
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_genres_path, class: 'btn btn-outline-secondary w-auto' do %>
      ジャンル一覧
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary w-auto' do %>
    　ログアウト
    <% end %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to about_path, class: 'btn btn-outline-secondary w-auto' do %>
      About
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_items_path, class: 'btn btn-outline-secondary w-auto' do %>
      商品一覧
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to new_customer_registration_path, class: 'btn btn-outline-secondary w-auto' do %>
      新規登録
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to new_admin_session_path, class: 'btn btn-outline-secondary w-auto' do %>
      ログイン
    <% end %>
  </li>
<% end %>

app/views/layouts/_customer_header.html.erb
<div class="row">
  <div class="col-sm-12">
    <% if customer_signed_in? %>
      <%= "ようこそ、#{ current_customer.name } さん！" %>
    <% end %>
  </div>
</div>
<% if customer_signed_in? %>
  <li class="nav-item">
    <%= link_to public_mypage_path, class: 'btn btn-outline-secondary w-auto' do %>
      マイページ
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to public_items_path, class: 'btn btn-outline-secondary w-auto' do %>
      商品一覧
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to public_cart_items_path, class: 'btn btn-outline-secondary w-auto' do %>
      カート
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary w-auto' do %>
    　ログアウト
    <% end %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to about_path, class: 'btn btn-outline-secondary w-auto' do %>
      About
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to public_items_path, class: 'btn btn-outline-secondary w-auto' do %>
      商品一覧
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to new_customer_registration_path, class: 'btn btn-outline-secondary w-auto' do %>
      新規登録
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to new_customer_session_path, class: 'btn btn-outline-secondary w-auto' do %>
      ログイン
    <% end %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div data-turbolinks="false">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
            <h1 class="navbar-brand">LOGO</h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <% if request.url&.include?('admin') %>
                    <%= render partial: "layouts/admin_header" %>
                  <% else %>
                    <%= render partial: "layouts/customer_header" %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <main>
      <%= yield %>
    <main>
  </body>
</html>